DELETE FROM GRADE_REPORT;
DELETE FROM PREREQUISITE;
DELETE FROM SECTION;
DELETE FROM COURSE;
DELETE FROM STUDENT;

INSERT INTO STUDENT VALUES ('Patel', 1, 4, 'CS');
INSERT INTO STUDENT VALUES ('Singh', 2, 3, 'CS');
INSERT INTO STUDENT VALUES ('Chen', 3, 2, 'CS');
INSERT INTO STUDENT VALUES ('Williams', 4, 4, 'CS');
INSERT INTO STUDENT VALUES ('Garcia', 5, 1, 'CS');
INSERT INTO STUDENT VALUES ('Kim', 6, 3, 'CS');
INSERT INTO STUDENT VALUES ('Brown', 7, 2, 'CS');
INSERT INTO STUDENT VALUES ('Ahmed', 8, 4, 'CS');
INSERT INTO STUDENT VALUES ('Lee', 9, 1, 'CS');
INSERT INTO STUDENT VALUES ('Martinez', 10, 3, 'CS');

INSERT INTO COURSE VALUES ('Computer Science I', 'CPS109', 1, 'CS');
INSERT INTO COURSE VALUES ('Computer Science II', 'CPS209', 1, 'CS');
INSERT INTO COURSE VALUES ('Data Structures', 'CPS305', 1, 'CS');
INSERT INTO COURSE VALUES ('Database Systems I', 'CPS510', 1, 'CS');
INSERT INTO COURSE VALUES ('Operating Systems I', 'CPS590', 1, 'CS');
INSERT INTO COURSE VALUES ('Algorithms', 'CPS616', 1, 'CS');
INSERT INTO COURSE VALUES ('Computer Networks I', 'CPS706', 1, 'CS');
INSERT INTO COURSE VALUES ('Machine Learning', 'CPS803', 1, 'CS');
INSERT INTO COURSE VALUES ('Discrete Mathematics I', 'MTH110', 1, 'MATH');

INSERT INTO SECTION VALUES (101, 'CPS109', 'Fall', 22, 'Marshall');
INSERT INTO SECTION VALUES (102, 'CPS209', 'Winter', 23, 'Harley');
INSERT INTO SECTION VALUES (103, 'CPS305', 'Fall', 23, 'Varghese');
INSERT INTO SECTION VALUES (104, 'CPS510', 'Fall', 24, 'Sadeghian');
INSERT INTO SECTION VALUES (105, 'CPS590', 'Winter', 24, 'Woungang');
INSERT INTO SECTION VALUES (106, 'CPS616', 'Winter', 25, 'Woungang');
INSERT INTO SECTION VALUES (107, 'CPS706', 'Winter', 25, 'Abhari');
INSERT INTO SECTION VALUES (108, 'CPS803', 'Fall', 25, 'Sadeghian');
INSERT INTO SECTION VALUES (109, 'MTH110', 'Fall', 22, 'Grinshpan');

INSERT INTO GRADE_REPORT VALUES (1, 101, 'A');
INSERT INTO GRADE_REPORT VALUES (1, 102, 'A');
INSERT INTO GRADE_REPORT VALUES (1, 103, 'B');
INSERT INTO GRADE_REPORT VALUES (1, 104, 'A');
INSERT INTO GRADE_REPORT VALUES (1, 105, 'A');
INSERT INTO GRADE_REPORT VALUES (1, 106, 'C');

INSERT INTO GRADE_REPORT VALUES (2, 101, 'B');
INSERT INTO GRADE_REPORT VALUES (2, 102, 'A');
INSERT INTO GRADE_REPORT VALUES (2, 103, 'B');

INSERT INTO GRADE_REPORT VALUES (3, 101, 'A');
INSERT INTO GRADE_REPORT VALUES (3, 109, 'A');

INSERT INTO GRADE_REPORT VALUES (4, 104, 'B');
INSERT INTO GRADE_REPORT VALUES (4, 105, 'A');
INSERT INTO GRADE_REPORT VALUES (4, 108, 'A');

INSERT INTO GRADE_REPORT VALUES (5, 101, 'B');
INSERT INTO GRADE_REPORT VALUES (5, 109, 'C');

INSERT INTO GRADE_REPORT VALUES (6, 103, 'A');
INSERT INTO GRADE_REPORT VALUES (6, 104, 'A');
INSERT INTO GRADE_REPORT VALUES (6, 106, 'B');

INSERT INTO GRADE_REPORT VALUES (7, 101, 'C');
INSERT INTO GRADE_REPORT VALUES (7, 102, 'B');

INSERT INTO GRADE_REPORT VALUES (8, 105, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 106, 'A');
INSERT INTO GRADE_REPORT VALUES (8, 107, 'B');

INSERT INTO GRADE_REPORT VALUES (9, 101, 'A');
INSERT INTO GRADE_REPORT VALUES (9, 109, 'B');

INSERT INTO GRADE_REPORT VALUES (10, 102, 'B');
INSERT INTO GRADE_REPORT VALUES (10, 103, 'B');
INSERT INTO GRADE_REPORT VALUES (10, 104, 'A');

INSERT INTO PREREQUISITE VALUES ('CPS209', 'CPS109');
INSERT INTO PREREQUISITE VALUES ('CPS305', 'CPS209');
INSERT INTO PREREQUISITE VALUES ('CPS510', 'CPS305');
INSERT INTO PREREQUISITE VALUES ('CPS616', 'CPS305');
INSERT INTO PREREQUISITE VALUES ('CPS590', 'CPS209');
INSERT INTO PREREQUISITE VALUES ('CPS706', 'CPS590');
INSERT INTO PREREQUISITE VALUES ('CPS803', 'CPS616');

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SECTION;
SELECT * FROM GRADE_REPORT;
SELECT * FROM PREREQUISITE;

SELECT S.Name, G.Grade, C.Course_name, C.Credit_hours
FROM STUDENT S, GRADE_REPORT G, SECTION SEC, COURSE C
WHERE G.Student_number = S.Student_number 
AND G.Section_identifier = SEC.Section_identifier 
AND SEC.Course_number = C.Course_number
AND S.Name = 'Patel';

SELECT ora_database_name FROM dual;
SELECT table_name FROM user_tables WHERE table_name = 'STUDENT';

SELECT COUNT(*) FROM STUDENT;


SELECT S.Name, C.Course_name, G.Grade, C.Credit_hours
FROM STUDENT S, GRADE_REPORT G, SECTION SEC, COURSE C
WHERE G.Student_number = S.Student_number
AND G.Section_identifier = SEC.Section_identifier
AND SEC.Course_number = C.Course_number
AND S.Name = 'Patel';